import { ClubEvent } from '../types';

export const defaultEvents: ClubEvent[] = [
  {
    id: 'internal-hackathon',
    title: 'Internal Hackathon',
    description: 'A high-energy build sprint where Aurix teams prototype bold technical solutions.',
    date: '2026-06-15',
    venue: 'Innovation Lab',
    category: 'hackathon',
    image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80',
    registrationOpen: true,
    createdAt: null,
  },
  {
    id: 'web-development-workshop',
    title: 'Web Development Workshop',
    description: 'Hands-on training for React, TypeScript, API design, deployment, and polished UI systems.',
    date: '2026-06-22',
    venue: 'Computer Center',
    category: 'workshop',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
    registrationOpen: true,
    createdAt: null,
  },
  {
    id: 'ai-robotics-bootcamp',
    title: 'AI & Robotics Bootcamp',
    description: 'Explore intelligent systems, embedded hardware, rapid prototyping, and automation workflows.',
    date: '2026-07-03',
    venue: 'Robotics Studio',
    category: 'bootcamp',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=80',
    registrationOpen: true,
    createdAt: null,
  },
  {
    id: 'ui-ux-design-sprint',
    title: 'UI/UX Design Sprint',
    description: 'A focused product design sprint covering research, wireframes, prototypes, and presentation.',
    date: '2026-07-12',
    venue: 'Design Studio',
    category: 'design',
    image: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=1200&q=80',
    registrationOpen: true,
    createdAt: null,
  },
  {
    id: 'startup-ideathon',
    title: 'Startup Ideathon',
    description: 'Pitch innovation challenges, validate product ideas, and build leadership through teams.',
    date: '2026-07-20',
    venue: 'Seminar Hall',
    category: 'ideathon',
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80',
    registrationOpen: true,
    createdAt: null,
  },
];
